image: harbor.intsig.net/base/resty_busted

before_script:
    - cp lib/http_test.lua /usr/local/openresty/lualib/
    - cp busted /usr/local/openresty/luajit/bin/busted
busted:
  script:
    - busted -p test_ -m example/?.lua example

test:
  services:
    - name: kennethreitz/httpbin
      alias: httpbin
  script:
    - export HTTPBIN_SERIVCE_IP=$(cat /etc/hosts | awk '{if ($2 == "httpbin") print $1;}')
    - busted test/*

http_test_exapmle:
  script:
    - openresty  -p `pwd`/example/customer -c conf/nginx.conf
    - busted example/customer_test.lua