image: harbor.intsig.net/base/resty_busted

before_script:
    - luarocks install ljsonschema
    - luarocks --server=http://rocks.moonscript.org install lyaml
    - cp lib/http_test.lua /usr/local/openresty/lualib/

busted:
  script:
    - busted -p test_ -m example/?.lua example

test:
  script:
    - busted test/*

http_test_exapmle:
  script:
    - openresty  -p `pwd`/example/customer -c conf/nginx.conf
    - busted example/customer_test.lua